# This file only lists settings that are different from the default ones as all configurations inherit from default options linked below
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
  # Cop names are displayed in offense messages.
  DisplayCopNames: true
  # Style guide URLs are displayed in offense messages.
  DisplayStyleGuide: true

############################## DISABLED ##############################

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

############################## ENABLED ##############################

# Align the elements of a hash literal if they span more than one line.
Style/AlignHash:
  # Alignment of entries using hash rocket as separator. Valid values are:
  #
  # key - left alignment of keys
  #   'a' => 2
  #   'bb' => 3
  # separator - alignment of hash rockets, keys are right aligned
  #    'a' => 2
  #   'bb' => 3
  # table - left alignment of keys, hash rockets, and values
  #   'a'  => 2
  #   'bb' => 3
  EnforcedHashRocketStyle: key
  # Alignment of entries using colon as separator. Valid values are:
  #
  # key - left alignment of keys
  #   a: 0
  #   bb: 1
  # separator - alignment of colons, keys are right aligned
  #    a: 0
  #   bb: 1
  # table - left alignment of keys and values
  #   a:  0
  #   bb: 1
  EnforcedColonStyle: key

Style/AlignParameters:
  # Alignment of parameters in multi-line method calls.
  #
  # The `with_first_parameter` style aligns the following lines along the same
  # column as the first parameter.
  #
  #     method_call(a,
  #                 b)
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with the method call.
  #
  #     method_call(a,
  #       b)
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/MultilineOperationIndentation:
  # Indentation of the right hand side operand in binary operations that span more than one line
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 100
