version: '2'
services:
  db:
    container_name: bdv-db
    env_file:
      - docker-compose.env
    image: postgres:9.5.1
    ports:
      # From EXPOSE in postgres Dockerfile
      - 5432:5432

  development:
    build: .
    # With 0.0.0.0, it is available from outside
    command: bundle exec rackup -o 0.0.0.0
    container_name: bdv-development
    env_file:
      - docker-compose.env
    environment:
      - RACK_ENV=development
    links:
      - db:db
    ports:
      - 9292:9292
    volumes:
      # /app is the same as WORKDIR in Dockerfile
      - .:/app

  test:
    build: .
    command: bundle exec rake test
    container_name: bdv-test
    env_file:
      - docker-compose.env
    environment:
      - RACK_ENV=test
    links:
      - db:db
    volumes:
      # /app is the same as WORKDIR in Dockerfile
      - .:/app
